# Auto-generated question data from dev/data/*.js files
QUESTIONS = [
    {
        "level_id": 1,
        "type": "填空题",
        "content": "<code>10 + 5 * 2</code> 的结果是 ",
        "options": None,
        "answer": "20",
        "knowledge_meaning": "先算乘法5×2=10，再算加法10+10=20。",
        "knowledge_rule": "乘除比加减优先级高，先算5×2。",
        "knowledge_error": "容易先算10+5=15，再×2=30。记住：先乘除后加减！",
        "knowledge_example": "<code>10 + 5 * 2 = 20</code><br><code>(10 + 5) * 2 = 30</code>",
        "sort_order": 0,
    },
    {
        "level_id": 1,
        "type": "选择题",
        "content": "下列哪个表达式结果为奇数？",
        "options": [{"letter": "A", "text": "<code>10 % 2</code>"}, {"letter": "B", "text": "<code>15 % 2</code>"}, {"letter": "C", "text": "<code>20 % 2</code>"}, {"letter": "D", "text": "<code>100 % 2</code>"}],
        "answer": "B",
        "knowledge_meaning": "%是取余数，15÷2=7余1，所以15%2=1（奇数）。",
        "knowledge_rule": "对2取余：结果0是偶数，结果1是奇数。",
        "knowledge_error": "不要把%和/搞混，/是除法，%是取余数。",
        "knowledge_example": "<code>15 % 2 = 1</code>（奇数）<br><code>14 % 2 = 0</code>（偶数）",
        "sort_order": 1,
    },
    {
        "level_id": 1,
        "type": "填空题",
        "content": "<code>17 // 5</code> 的结果是 ",
        "options": None,
        "answer": "3",
        "knowledge_meaning": "17÷5=3.4，//是整除，只取整数部分3。",
        "knowledge_rule": "//只取结果的整数部分，小数部分不要。",
        "knowledge_error": "不是四舍五入！17//5=3，不是3.4，也不是4。",
        "knowledge_example": "<code>17 // 5 = 3</code><br><code>17 / 5 = 3.4</code>",
        "sort_order": 2,
    },
    {
        "level_id": 1,
        "type": "判断题",
        "content": "<code>2 ** 3 ** 2</code> 的结果是 <code>64</code>。",
        "options": None,
        "answer": "false",
        "knowledge_meaning": "**从右往左算：先算3**2=9，再算2**9=512。",
        "knowledge_rule": "**是右结合的，a**b**c等于a**(b**c)。",
        "knowledge_error": "容易从左往右算成(2**3)**2=8**2=64。",
        "knowledge_example": "<code>2 ** 3 ** 2 = 2 ** 9 = 512</code><br><code>(2 ** 3) ** 2 = 64</code>",
        "sort_order": 3,
    },
    {
        "level_id": 1,
        "type": "选择题",
        "content": "表达式 <code>(-10) % 3</code> 的结果是？",
        "options": [{"letter": "A", "text": "-1"}, {"letter": "B", "text": "-2"}, {"letter": "C", "text": "1"}, {"letter": "D", "text": "2"}],
        "answer": "D",
        "knowledge_meaning": "(-10)÷3=-3余-1，但Python规定结果要与除数同号，所以结果是2。简单记：Python取模结果永远是正的（当除数是正数时）。",
        "knowledge_rule": "Python的%结果符号与除数相同，除数3是正数，所以结果是正数。",
        "knowledge_error": "不要以为负数取模结果是负数！Python保证结果和除数同号。",
        "knowledge_example": "<code>(-10) % 3 = 2</code><br><code>10 % (-3) = -2</code>",
        "sort_order": 4,
    },
    {
        "level_id": 2,
        "type": "判断题",
        "content": "<code>3 == 3.0</code> 的结果是 <code>True</code>。",
        "options": None,
        "answer": "true",
        "knowledge_meaning": "3和3.0数值相等，==只比较值，不比较类型。",
        "knowledge_rule": "整数和浮点数只要数值相等，==就返回True。",
        "knowledge_error": "不要把==和is搞混！==比较值，is比较内存地址。",
        "knowledge_example": "<code>3 == 3.0</code> → <code>True</code><br><code>3 is 3.0</code> → <code>False</code>",
        "sort_order": 0,
    },
    {
        "level_id": 2,
        "type": "选择题",
        "content": "下列表达式中，结果为 <code>False</code> 的是？",
        "options": [{"letter": "A", "text": "<code>\"hello\" == \"hello\"</code>"}, {"letter": "B", "text": "<code>[1,2] == [1,2]</code>"}, {"letter": "C", "text": "<code>\"abc\" < \"bcd\"</code>"}, {"letter": "D", "text": "<code>\"abc\" > \"abcd\"</code>"}],
        "answer": "D",
        "knowledge_meaning": "\"abc\"比\"abcd\"短，所以\"abc\"小于\"abcd\"，\"abc\">\"abcd\"是错的。",
        "knowledge_rule": "字符串比较时，较短的字符串更小（当前缀相同时）。",
        "knowledge_error": "不要觉得\"abc\"更长所以更大！字典序中短的在前。",
        "knowledge_example": "<code>\"abc\" > \"abcd\"</code> → <code>False</code><br><code>\"abc\" < \"abd\"</code> → <code>True</code>",
        "sort_order": 1,
    },
    {
        "level_id": 2,
        "type": "填空题",
        "content": "<code>10 != 9</code> 的结果是 ",
        "options": None,
        "answer": "True",
        "knowledge_meaning": "10不等于9，所以正确。!=就是\"不等于\"的意思。",
        "knowledge_rule": "!=表示不等于，相等返回False，不等返回True。",
        "knowledge_error": "注意不要写成=!，那是错的。!=是!=，顺序不能换。",
        "knowledge_example": "<code>10 != 9</code> → <code>True</code><br><code>10 != 10</code> → <code>False</code>",
        "sort_order": 2,
    },
    {
        "level_id": 2,
        "type": "选择题",
        "content": "表达式 <code>5 <= 5.0</code> 的结果是？",
        "options": [{"letter": "A", "text": "True"}, {"letter": "B", "text": "False"}, {"letter": "C", "text": "报错"}, {"letter": "D", "text": "None"}],
        "answer": "A",
        "knowledge_meaning": "5和5.0相等，5<=5.0当然成立，返回True。",
        "knowledge_rule": "Python中整数和浮点数可以直接比较，会自动转换类型。",
        "knowledge_error": "不要以为不同类型不能比较！Python数值类型可以跨类型比较。",
        "knowledge_example": "<code>5 <= 5.0</code> → <code>True</code><br><code>5 == 5.0</code> → <code>True</code>",
        "sort_order": 3,
    },
    {
        "level_id": 2,
        "type": "判断题",
        "content": "在Python中，<code>None == 0</code> 的结果是 <code>True</code>。",
        "options": None,
        "answer": "false",
        "knowledge_meaning": "None是Python的\"空\"，不等于0，也不等于False，各是各的。",
        "knowledge_rule": "None只和None相等，和其他任何值都不等。",
        "knowledge_error": "None不是0，不是空字符串，不是False，就是个特殊的\"空\"。",
        "knowledge_example": "<code>None == 0</code> → <code>False</code><br><code>None == False</code> → <code>False</code><br><code>None == None</code> → <code>True</code>",
        "sort_order": 4,
    },
    {
        "level_id": 3,
        "type": "填空题",
        "content": "<code>3 > 2 and 5 > 4</code> 的结果是 ",
        "options": None,
        "answer": "True",
        "knowledge_meaning": "3>2是真，5>4是真，真and真=真。",
        "knowledge_rule": "and两边都为True结果才是True，有一个是False就是False。",
        "knowledge_error": "and不是\"和\"的意思，是\"并且\"，两边都要满足才成立。",
        "knowledge_example": "<code>True and True</code> → <code>True</code><br><code>True and False</code> → <code>False</code>",
        "sort_order": 0,
    },
    {
        "level_id": 3,
        "type": "选择题",
        "content": "表达式 <code>not (3 < 5)</code> 的结果是？",
        "options": [{"letter": "A", "text": "3 < 5"}, {"letter": "B", "text": "True"}, {"letter": "C", "text": "报错"}, {"letter": "D", "text": "False"}],
        "answer": "D",
        "knowledge_meaning": "先算括号里3<5=真，再not真=假，所以结果是False。",
        "knowledge_rule": "not是取反：not True=False，not False=True。",
        "knowledge_error": "not 3<5容易报错，因为<优先级高于not。要加括号not(3<5)。",
        "knowledge_example": "<code>not (3 < 5)</code> = <code>not True</code> = <code>False</code>",
        "sort_order": 1,
    },
    {
        "level_id": 3,
        "type": "填空题",
        "content": "<code>True or False and False</code> 的结果是 ",
        "options": None,
        "answer": "True",
        "knowledge_meaning": "and优先级高于or，先算False and False=False，再算True or False=True。",
        "knowledge_rule": "优先级：not > and > or。记忆：N-A-O（不打啊哦？）",
        "knowledge_error": "容易从左往右算成True or False=True就结束了，忘了先算and。",
        "knowledge_example": "<code>True or False and False</code> = <code>True or False</code> = <code>True</code><br><code>(True or False) and False</code> = <code>False</code>",
        "sort_order": 2,
    },
    {
        "level_id": 3,
        "type": "选择题",
        "content": "下列哪个表达式会输出 <code>hello</code>？",
        "options": [{"letter": "A", "text": "<code>False and \"hello\"</code>"}, {"letter": "B", "text": "<code>True and \"\"</code>"}, {"letter": "C", "text": "<code>True and \"hello\"</code>"}, {"letter": "D", "text": "<code>\"\" and \"hello\"</code>"}],
        "answer": "C",
        "knowledge_meaning": "and/or不只是返回True/False，它返回实际参与的值！True and \"hello\"返回\"hello\"。",
        "knowledge_rule": "a and b：a为真返回b，a为假返回a。<br>a or b：a为真返回a，a为假返回b。",
        "knowledge_error": "不要以为and/or只返回布尔值，它们返回的是实际的值！",
        "knowledge_example": "<code>True and \"hello\"</code> → <code>\"hello\"</code><br><code>False and \"hello\"</code> → <code>False</code>",
        "sort_order": 3,
    },
    {
        "level_id": 3,
        "type": "判断题",
        "content": "<code>1 and 0</code> 的结果是 <code>False</code>。",
        "options": None,
        "answer": "true",
        "knowledge_meaning": "1是真，0是假。1 and 0返回的是第二个值0（0就是False）。",
        "knowledge_rule": "1 and 0：第一个值1为真，所以返回第二个值0。",
        "knowledge_error": "注意！返回的是0，不是False。虽然0在布尔语境下等于False，但它们不一样。",
        "knowledge_example": "<code>1 and 0</code> → <code>0</code>（返回的是0，不是False）<br><code>bool(1 and 0)</code> → <code>False</code>",
        "sort_order": 4,
    },
    {
        "level_id": 4,
        "type": "选择题",
        "content": "执行 <code>x = 5; x += 3</code> 后，x 的值是？",
        "options": [{"letter": "A", "text": "3"}, {"letter": "B", "text": "8"}, {"letter": "C", "text": "5"}, {"letter": "D", "text": "53"}],
        "answer": "B",
        "knowledge_meaning": "x+=3就是x=x+3，所以5+3=8。",
        "knowledge_rule": "x += n 等于 x = x + n。+=就是\"加上再赋值\"。",
        "knowledge_error": "不要把+=当成字符串连接！+=是数学加法。",
        "knowledge_example": "<code>x = 5</code><br><code>x += 3</code> → <code>x = 5 + 3 = 8</code>",
        "sort_order": 0,
    },
    {
        "level_id": 4,
        "type": "填空题",
        "content": "执行以下代码后：<br><code>x = 10<br>x -= 3<br>x *= 2</code><br>x 的值是 ",
        "options": None,
        "answer": "14",
        "knowledge_meaning": "x=10→x=10-3=7→x=7×2=14。每一步都用最新的x值。",
        "knowledge_rule": "复合赋值从左到右执行，每一步都用上一步的结果。",
        "knowledge_error": "容易用初始值10算：10-3=7，10×2=20。记住每次都基于上一步的结果！",
        "knowledge_example": "<code>x = 10</code><br><code>x -= 3</code> → <code>x = 7</code><br><code>x *= 2</code> → <code>x = 14</code>",
        "sort_order": 1,
    },
    {
        "level_id": 4,
        "type": "选择题",
        "content": "表达式 <code>y = 5; y /= 2; y</code> 的结果是？",
        "options": [{"letter": "A", "text": "2"}, {"letter": "B", "text": "2.0"}, {"letter": "C", "text": "2.5"}, {"letter": "D", "text": "报错"}],
        "answer": "C",
        "knowledge_meaning": "y/=2就是y=y/2，5除以2等于2.5。/总是返回浮点数。",
        "knowledge_rule": "y /= 2 = y = y / 2。注意/是普通除法，返回浮点数。",
        "knowledge_error": "不要和//搞混！/返回小数，//才是整除。",
        "knowledge_example": "<code>y = 5</code><br><code>y /= 2</code> → <code>y = 5 / 2 = 2.5</code>",
        "sort_order": 2,
    },
    {
        "level_id": 4,
        "type": "判断题",
        "content": "<code>x = 10; x %= 3</code> 执行后，x 的值是 1。",
        "options": None,
        "answer": "true",
        "knowledge_meaning": "x%=3就是x=x%3，10除以3余1，所以x=1。",
        "knowledge_rule": "x %= n = x = x % n。%是取余数。",
        "knowledge_error": "不要把%当成除法！10%3是取余数，不是10除以3。",
        "knowledge_example": "<code>x = 10</code><br><code>x %= 3</code> → <code>x = 10 % 3 = 1</code>",
        "sort_order": 3,
    },
    {
        "level_id": 4,
        "type": "选择题",
        "content": "关于赋值运算符，以下说法正确的是？",
        "options": [{"letter": "A", "text": "<code>x += y</code> 等价于 <code>x =+ y</code>"}, {"letter": "B", "text": "<code>x -= y</code> 等价于 <code>x = y - x</code>"}, {"letter": "C", "text": "<code>x *= y</code> 等价于 <code>x = x * (y - 1)</code>"}, {"letter": "D", "text": "<code>x **= y</code> 等价于 <code>x = x ** y</code>"}],
        "answer": "D",
        "knowledge_meaning": "x**=y就是x=x**y，即x的y次方。比如x=2,y=3，则x=2**3=8。",
        "knowledge_rule": "x op= y 等于 x = x op y，顺序是固定的。",
        "knowledge_error": "+=是+和=挨着写的，不能写成=+！顺序很重要。",
        "knowledge_example": "<code>x **= y</code> = <code>x = x ** y</code><br><code>x = 2, x **= 3</code> → <code>x = 8</code>",
        "sort_order": 4,
    },
    {
        "level_id": 5,
        "type": "判断题",
        "content": "<code>\"a\" in \"apple\"</code> 的结果是 <code>True</code>。",
        "options": None,
        "answer": "true",
        "knowledge_meaning": "\"a\"在\"apple\"里能找到，所以返回True。in就是\"在...里\"的意思。",
        "knowledge_rule": "x in y：检查x是否是y的子串/元素。找到了返回True。",
        "knowledge_error": "注意大小写！\"A\" in \"apple\"是False，Python区分大小写。",
        "knowledge_example": "<code>\"a\" in \"apple\"</code> → <code>True</code><br><code>\"A\" in \"apple\"</code> → <code>False</code>",
        "sort_order": 0,
    },
    {
        "level_id": 5,
        "type": "选择题",
        "content": "表达式 <code>3 in [1, 2, 3, 4]</code> 的结果是？",
        "options": [{"letter": "A", "text": "True"}, {"letter": "B", "text": "False"}, {"letter": "C", "text": "3"}, {"letter": "D", "text": "报错"}],
        "answer": "A",
        "knowledge_meaning": "3在列表[1,2,3,4]中能找到，所以返回True。",
        "knowledge_rule": "in检查元素是否在列表/元组/集合中，找到了就是True。",
        "knowledge_error": "不要把in当成索引！3是元素，不是索引（索引是0,1,2,3）。",
        "knowledge_example": "<code>3 in [1, 2, 3, 4]</code> → <code>True</code><br><code>0 in [1, 2, 3, 4]</code> → <code>False</code>",
        "sort_order": 1,
    },
    {
        "level_id": 5,
        "type": "填空题",
        "content": "<code>\"key\" not in {\"name\": \"Tom\", \"key\": \"value\"}</code> 的结果是 ",
        "options": None,
        "answer": "False",
        "knowledge_meaning": "字典里有\"key\"这个键，所以\"key not in\"是False。not in就是\"不在...里\"。",
        "knowledge_rule": "not in是in的反面。在里面返回False，不在里面返回True。",
        "knowledge_error": "字典的成员是键不是值！\"name\" in dict检查的是键，不是\"Tom\"。",
        "knowledge_example": "<code>\"key\" in {\"name\": \"Tom\"}</code> → <code>True</code><br><code>\"Tom\" in {\"name\": \"Tom\"}</code> → <code>False</code>",
        "sort_order": 2,
    },
    {
        "level_id": 5,
        "type": "选择题",
        "content": "以下哪个表达式的结果是 <code>True</code>？",
        "options": [{"letter": "A", "text": "<code>\"3\" in [1, 2, 3]</code>"}, {"letter": "B", "text": "<code>3 in [1, 2, 3]</code>"}, {"letter": "C", "text": "<code>\"ab\" in \"a,b,c\"</code>"}, {"letter": "D", "text": "<code>None in [None, 1, 2]</code>"}],
        "answer": "B",
        "knowledge_meaning": "3是整数，和列表里的3匹配。A错是因为\"3\"是字符串。C错是因为\"ab\"不是\"a,b,c\"的子串。",
        "knowledge_rule": "in检查类型和值都匹配。字符串\"3\"不等于整数3。",
        "knowledge_error": "注意类型！\"3\"不等于3，\"ab\"不等于\"a,b,c\"（后者包含逗号）。",
        "knowledge_example": "<code>\"3\" in [1, 2, 3]</code> → <code>False</code>（类型不同）<br><code>3 in [1, 2, 3]</code> → <code>True</code>",
        "sort_order": 3,
    },
    {
        "level_id": 5,
        "type": "判断题",
        "content": "<code>(1, 2) in [(1, 2), (3, 4)]</code> 的结果是 <code>True</code>。",
        "options": None,
        "answer": "true",
        "knowledge_meaning": "(1,2)作为整体是列表的第一个元素，所以能找到，返回True。",
        "knowledge_rule": "元组可以整体作为列表的元素，in是完整匹配。",
        "knowledge_error": "注意是整体匹配！(1,2)是查\"元组(1,2)\"在不在，不是查1或2在不在。",
        "knowledge_example": "<code>(1, 2) in [(1, 2), (3, 4)]</code> → <code>True</code><br><code>1 in [(1, 2), (3, 4)]</code> → <code>False</code>",
        "sort_order": 4,
    },
    {
        "level_id": 6,
        "type": "选择题",
        "content": "表达式 <code>not 0</code> 的结果是？",
        "options": [{"letter": "A", "text": "False"}, {"letter": "B", "text": "True"}, {"letter": "C", "text": "0"}, {"letter": "D", "text": "报错"}],
        "answer": "B",
        "knowledge_meaning": "0在Python里是假，not假=真，所以not 0=True。",
        "knowledge_rule": "not真=假，not假=真。0等于假，非0等于真。",
        "knowledge_error": "不要以为not 0=False！0是假，取反后是True。",
        "knowledge_example": "<code>not 0</code> → <code>True</code><br><code>not 1</code> → <code>False</code>",
        "sort_order": 0,
    },
    {
        "level_id": 6,
        "type": "填空题",
        "content": "<code>10 // 3 + 10 % 3</code> 的结果是 ",
        "options": None,
        "answer": "4",
        "knowledge_meaning": "先算//：10//3=3；再算%：10%3=1；最后算+：3+1=4。",
        "knowledge_rule": "//和%优先级相同，比+高。从左到右算。",
        "knowledge_error": "容易忘记优先级，应该先算整除和取模，再做加法。",
        "knowledge_example": "<code>10 // 3 = 3</code><br><code>10 % 3 = 1</code><br><code>3 + 1 = 4</code>",
        "sort_order": 1,
    },
    {
        "level_id": 6,
        "type": "判断题",
        "content": "<code>\"py\" and \"thon\"</code> 的结果是 <code>\"thon\"</code>。",
        "options": None,
        "answer": "true",
        "knowledge_meaning": "\"py\"是真（非空字符串），所以返回第二个值\"thon\"。and/or返回的是实际值，不只是True/False！",
        "knowledge_rule": "a and b：a为真返回b，a为假返回a。",
        "knowledge_error": "不要以为\"py\" and \"thon\"返回True！它返回的是\"thon\"这个字符串。",
        "knowledge_example": "<code>\"py\" and \"thon\"</code> → <code>\"thon\"</code><br><code>\"\" and \"thon\"</code> → <code>\"\"</code>",
        "sort_order": 2,
    },
    {
        "level_id": 6,
        "type": "选择题",
        "content": "执行 <code>x = 5; x *= 3 + 2</code> 后，x 的值是？",
        "options": [{"letter": "A", "text": "20"}, {"letter": "B", "text": "21"}, {"letter": "C", "text": "25"}, {"letter": "D", "text": "30"}],
        "answer": "C",
        "knowledge_meaning": "先算右边3+2=5，再算x*=5，即5*5=25。记住先算右边！",
        "knowledge_rule": "x *= a + b 等于 x = x * (a + b)，不是 x = x * a + b。",
        "knowledge_error": "容易错把右边表达式拆开算，正确做法是先完整计算右侧。",
        "knowledge_example": "<code>x = 5</code><br><code>x *= 3 + 2</code> = <code>x *= 5</code> = <code>x = 5 * 5 = 25</code>",
        "sort_order": 3,
    },
    {
        "level_id": 6,
        "type": "填空题",
        "content": "<code>\"hello\"[-1]</code> 的结果是 ",
        "options": None,
        "answer": "o",
        "knowledge_meaning": "\"hello\"的最后一个字符是\"o\"。-1就是倒数第一个。",
        "knowledge_rule": "正数从0开始，负数从-1开始表示倒数位置。",
        "knowledge_error": "不要以为-1是第一个！-1表示最后一个字符。",
        "knowledge_example": "<code>\"hello\"[-1]</code> → <code>\"o\"</code><br><code>\"hello\"[-2]</code> → <code>\"l\"</code>",
        "sort_order": 4,
    },
    {
        "level_id": 7,
        "type": "选择题",
        "content": "在Python中，<code>if</code> 语句条件部分的末尾必须使用什么符号？",
        "options": [{"letter": "A", "text": "分号 ;"}, {"letter": "B", "text": "逗号 ,"}, {"letter": "C", "text": "冒号 :"}, {"letter": "D", "text": "句号 ."}],
        "answer": "C",
        "knowledge_meaning": "冒号在Python中代表接下来是一个代码块（需要缩进）。",
        "knowledge_rule": "所有复合语句（如 if, for, while, def 等）的首行都必须以冒号结尾。",
        "knowledge_error": "初学者极易漏写冒号，这会导致 SyntaxError（语法错误）。",
        "knowledge_example": "<code>if x > 0:</code><br><code>&nbsp;&nbsp;&nbsp;&nbsp;print(\"Yes\")</code>",
        "sort_order": 0,
    },
    {
        "level_id": 7,
        "type": "判断题",
        "content": "在 <code>if</code> 语句下方属于该条件分支的代码，必须要有相同的缩进。",
        "options": None,
        "answer": "true",
        "knowledge_meaning": "Python通过缩进来判断代码的层级关系，缩进相同的代码属于同一个代码块。",
        "knowledge_rule": "标准缩进是4个空格，同一代码块内的缩进空格数必须绝对一致。",
        "knowledge_error": "不要混用Tab和空格，否则会报 IndentationError（缩进错误）。",
        "knowledge_example": "<code>if True:</code><br><code>&nbsp;&nbsp;&nbsp;&nbsp;a = 1</code><br><code>&nbsp;&nbsp;&nbsp;&nbsp;b = 2</code>",
        "sort_order": 1,
    },
    {
        "level_id": 7,
        "type": "填空题",
        "content": "执行代码：<br><code>x = 5<br>if x > 3:<br>&nbsp;&nbsp;&nbsp;&nbsp;x = x + 2<br>print(x)</code><br>输出结果是 ",
        "options": None,
        "answer": "7",
        "knowledge_meaning": "5大于3，条件成立，执行缩进块内的代码，x变为7。",
        "knowledge_rule": "只有if条件结果为True时，才会执行其内部的缩进代码。",
        "knowledge_error": "如果不注意判断条件是否成立，容易算错最终的变量值。",
        "knowledge_example": "条件成立，执行 <code>x = 5 + 2</code>。",
        "sort_order": 2,
    },
    {
        "level_id": 7,
        "type": "选择题",
        "content": "以下哪个 <code>if</code> 语句的写法是正确的？",
        "options": [{"letter": "A", "text": "<code>if a == 10:</code>"}, {"letter": "B", "text": "<code>if a = 10:</code>"}, {"letter": "C", "text": "<code>if (a == 10)</code>"}, {"letter": "D", "text": "<code>if a == 10</code>"}],
        "answer": "A",
        "knowledge_meaning": "正确写法必须包含比较运算符(==)和末尾的冒号(:)。",
        "knowledge_rule": "在条件判断中，判断相等必须用双等号 `==`，单等号 `=` 是赋值。",
        "knowledge_error": "写成 `if a = 10:` 是最常见的语法错误，Python不支持在if中直接赋值。",
        "knowledge_example": "<code>if a == 10:</code>",
        "sort_order": 3,
    },
    {
        "level_id": 7,
        "type": "填空题",
        "content": "执行代码：<br><code>a = 10<br>if a < 5:<br>&nbsp;&nbsp;&nbsp;&nbsp;a = 0<br>print(a)</code><br>输出结果是 ",
        "options": None,
        "answer": "10",
        "knowledge_meaning": "因为10 < 5为假（False），所以跳过缩进的代码，a的值保持不变。",
        "knowledge_rule": "如果条件为False，程序会跳过整个if代码块，继续执行后面的未缩进代码。",
        "knowledge_error": "不要盲目执行代码块里的内容，先判断条件真假！",
        "knowledge_example": "跳过 <code>a = 0</code>，直接执行 <code>print(a)</code>。",
        "sort_order": 4,
    },
    {
        "level_id": 8,
        "type": "判断题",
        "content": "<code>else</code> 语句可以单独使用，不需要前面有 <code>if</code> 语句。",
        "options": None,
        "answer": "false",
        "knowledge_meaning": "`else` 的意思是\"否则\"，它必须依附于前面的 `if`（或 for/while/try）存在，不能孤立存在。",
        "knowledge_rule": "一个标准的双分支结构是 `if...else...`，它们成对出现且缩进级别相同。",
        "knowledge_error": "单独写 `else:` 会直接报语法错误（SyntaxError）。",
        "knowledge_example": "正确：<code>if a > 0: ... else: ...</code>",
        "sort_order": 0,
    },
    {
        "level_id": 8,
        "type": "填空题",
        "content": "执行代码：<br><code>n = 4<br>if n % 2 == 0:<br>&nbsp;&nbsp;&nbsp;&nbsp;res = 1<br>else:<br>&nbsp;&nbsp;&nbsp;&nbsp;res = 2</code><br>res 的值是 ",
        "options": None,
        "answer": "1",
        "knowledge_meaning": "4能被2整除（余数为0），所以执行 if 分支，不执行 else 分支。",
        "knowledge_rule": "`if-else` 是互斥的，条件为True走if，为False走else，必定只走其中一条路。",
        "knowledge_error": "切忌两条路都执行。判断为真后，else块会被直接忽略。",
        "knowledge_example": "判断奇偶数是if-else的经典应用场景。",
        "sort_order": 1,
    },
    {
        "level_id": 8,
        "type": "选择题",
        "content": "关于 <code>else</code> 语句，以下说法错误的是？",
        "options": [{"letter": "A", "text": "<code>else</code> 后面不能加条件表达式"}, {"letter": "B", "text": "<code>else</code> 必须和对应的 <code>if</code> 对齐"}, {"letter": "C", "text": "一个 <code>if</code> 后面可以跟多个 <code>else</code>"}, {"letter": "D", "text": "<code>else</code> 后面也必须加冒号"}],
        "answer": "C",
        "knowledge_meaning": "一个 if 语句只能搭配最多一个 else（作为最后的保底分支）。",
        "knowledge_rule": "结构只能是 `if -> (0个或多个elif) -> (0或1个else)`。",
        "knowledge_error": "如果在代码中写两个并列的else，Python会报错。",
        "knowledge_example": "错误示范：<code>if x>0: ... else: ... else: ...</code>",
        "sort_order": 2,
    },
    {
        "level_id": 8,
        "type": "填空题",
        "content": "执行代码：<br><code>x = -5<br>if x >= 0:<br>&nbsp;&nbsp;&nbsp;&nbsp;x = x + 5<br>else:<br>&nbsp;&nbsp;&nbsp;&nbsp;x = x - 5</code><br>最后 x 的值是 ",
        "options": None,
        "answer": "-10",
        "knowledge_meaning": "-5 >= 0 为假，进入 else 分支，执行 -5 - 5 = -10。",
        "knowledge_rule": "仔细代入初始变量值，按照条件走向计算最终结果。",
        "knowledge_error": "注意负数的加减法，-5减去5是-10，不是0！",
        "knowledge_example": "走else分支：<code>x = -5 - 5</code>",
        "sort_order": 3,
    },
    {
        "level_id": 8,
        "type": "选择题",
        "content": "如果想判断一个数 <code>x</code> 是否非负，并在负数时将其变正，应该选？",
        "options": [{"letter": "A", "text": "<code>if x > 0: x = -x</code>"}, {"letter": "B", "text": "<code>if x < 0: x = -x</code>"}, {"letter": "C", "text": "<code>else x < 0: x = -x</code>"}, {"letter": "D", "text": "<code>if x < 0 else: x = -x</code>"}],
        "answer": "B",
        "knowledge_meaning": "负数才需要变正，所以条件是 `x < 0`，将其变成相反数 `-x` 即为正数。",
        "knowledge_rule": "这也是求绝对值（abs）的基础底层逻辑。",
        "knowledge_error": "C错在else后面不能加条件；D错在语法完全不通。",
        "knowledge_example": "当 x = -3 时，进入 `if x < 0`，执行 `x = -(-3)`，x变为3。",
        "sort_order": 4,
    },
    {
        "level_id": 9,
        "type": "选择题",
        "content": "在多分支判断中，<code>elif</code> 是哪个英文短语的缩写？",
        "options": [{"letter": "A", "text": "else if"}, {"letter": "B", "text": "every if"}, {"letter": "C", "text": "either if"}, {"letter": "D", "text": "end if"}],
        "answer": "A",
        "knowledge_meaning": "Python为了让代码更简洁，将 else if 组合成了 elif。",
        "knowledge_rule": "elif 必须用在 if 之后，else 之前。后面必须跟条件表达式和冒号。",
        "knowledge_error": "不要在Python里写 `else if`，会报语法错误，必须写成 `elif`。",
        "knowledge_example": "<code>elif score >= 80:</code>",
        "sort_order": 0,
    },
    {
        "level_id": 9,
        "type": "填空题",
        "content": "执行代码：<br><code>x = 8<br>if x > 10:<br>&nbsp;&nbsp;&nbsp;&nbsp;y = 1<br>elif x > 5:<br>&nbsp;&nbsp;&nbsp;&nbsp;y = 2<br>elif x > 0:<br>&nbsp;&nbsp;&nbsp;&nbsp;y = 3</code><br>y 的值是 ",
        "options": None,
        "answer": "2",
        "knowledge_meaning": "x是8，不大于10，看下一个条件；8大于5，条件成立，执行 y=2。",
        "knowledge_rule": "从上到下按顺序判断，只要有一个条件成立，执行后就会**立刻跳出**整个 if-elif 结构。",
        "knowledge_error": "不要因为8也大于0就执行 y=3。匹配到第一个满足的条件后就不会再往下判断了！",
        "knowledge_example": "这就是为什么多分支结构要注意条件的先后顺序。",
        "sort_order": 1,
    },
    {
        "level_id": 9,
        "type": "判断题",
        "content": "一个多分支结构可以只有 <code>if</code> 和多个 <code>elif</code>，而不需要 <code>else</code> 结尾。",
        "options": None,
        "answer": "true",
        "knowledge_meaning": "`else` 是可选的（作为所有条件都不满足时的默认操作）。如果不需要默认操作，完全可以省略。",
        "knowledge_rule": "`if-elif` 结构合法。如果没有任何条件满足，程序就直接略过整个结构继续向下执行。",
        "knowledge_error": "很多人误以为if语句最后必须用else兜底，其实不是强制的。",
        "knowledge_example": "<code>if a == 1: print(\"A\")<br>elif a == 2: print(\"B\")</code> （没有else完全合法）",
        "sort_order": 2,
    },
    {
        "level_id": 9,
        "type": "选择题",
        "content": "下面这段评级代码有一个逻辑漏洞，输入什么分数会得到错误的结果？<br><code>if score >= 60: return \"及格\"<br>elif score >= 90: return \"优秀\"</code>",
        "options": [{"letter": "A", "text": "50"}, {"letter": "B", "text": "70"}, {"letter": "C", "text": "85"}, {"letter": "D", "text": "95"}],
        "answer": "D",
        "knowledge_meaning": "输入95时，95>=60满足条件，直接返回\"及格\"并跳出，永远无法执行到\"优秀\"。",
        "knowledge_rule": "在使用大于(>)判断时，条件范围小的（如>=90）应该写在前面，范围大的写在后面。",
        "knowledge_error": "条件发生覆盖和重叠时，排在前面的条件会拦截排在后面的条件。",
        "knowledge_example": "正确写法应先判断 <code>if score >= 90</code>，再判断 <code>elif score >= 60</code>。",
        "sort_order": 3,
    },
    {
        "level_id": 9,
        "type": "填空题",
        "content": "执行代码：<br><code>a = 3<br>if a == 1: a += 1<br>elif a == 2: a += 2<br>else: a += 3</code><br>最终 a 的值是 ",
        "options": None,
        "answer": "6",
        "knowledge_meaning": "3既不等于1也不等于2，所以落入最后的else分支，执行 a = 3 + 3 = 6。",
        "knowledge_rule": "else 作为\"垃圾桶\"分支，收纳所有不符合前面条件的情况。",
        "knowledge_error": "别看错了初始值和运算符号，a += 3 就是 a = a + 3。",
        "knowledge_example": "<code>else:</code> 处理所有其他情况。",
        "sort_order": 4,
    },
    {
        "level_id": 10,
        "type": "判断题",
        "content": "在Python中，<code>if</code> 语句内部不可以再包含另一个 <code>if-else</code> 结构。",
        "options": None,
        "answer": "false",
        "knowledge_meaning": "条件语句是可以嵌套的，你可以在一个if里面再写if，层次理论上不限。",
        "knowledge_rule": "嵌套时一定要严格注意**缩进**。内部的if要比外部的if多一层缩进（通常多4个空格）。",
        "knowledge_error": "嵌套层数过多（超过3层）会导致代码像\"箭头\"一样，可读性极差，被称为\"回调地狱/嵌套地狱\"。",
        "knowledge_example": "<code>if 晴天:<br>&nbsp;&nbsp;if 有空:<br>&nbsp;&nbsp;&nbsp;&nbsp;去打球</code>",
        "sort_order": 0,
    },
    {
        "level_id": 10,
        "type": "填空题",
        "content": "执行代码：<br><code>x, y = 10, 5<br>if x > 5:<br>&nbsp;&nbsp;&nbsp;&nbsp;if y > 5:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ans = \"A\"<br>&nbsp;&nbsp;&nbsp;&nbsp;else:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ans = \"B\"<br>else:<br>&nbsp;&nbsp;&nbsp;&nbsp;ans = \"C\"</code><br>ans 的值是 ",
        "options": None,
        "answer": "B",
        "knowledge_meaning": "第一层 x>5(10>5) 成立；进入内层判断 y>5(5>5) 为假，走内层的 else，得到 \"B\"。",
        "knowledge_rule": "外层条件满足后，才会进入内层判断；内层的 else 只与同缩进级别的内层 if 匹配。",
        "knowledge_error": "不要把内层的 else 和外层的 else 看混了，对齐（缩进）是谁，就和谁配对！",
        "knowledge_example": "缩进决定了代码的归属关系。",
        "sort_order": 1,
    },
    {
        "level_id": 10,
        "type": "选择题",
        "content": "下面哪段代码等价于 <code>if a > 0 and b > 0:</code> ？",
        "options": [{"letter": "A", "text": "<code>if a > 0:<br>&nbsp;&nbsp;if b > 0:</code>"}, {"letter": "B", "text": "<code>if a > 0:<br>if b > 0:</code>"}, {"letter": "C", "text": "<code>if a > 0 or b > 0:</code>"}, {"letter": "D", "text": "<code>if a > 0 elif b > 0:</code>"}],
        "answer": "A",
        "knowledge_meaning": "嵌套的两个 if，意味着必须同时满足条件a且满足条件b才能进入最深层，逻辑上等同于 `and`。",
        "knowledge_rule": "可以通过逻辑运算符（and）来合并简单的嵌套 if，让代码更扁平化。",
        "knowledge_error": "B选项没有缩进，是两个并列的if，逻辑完全不同。",
        "knowledge_example": "优先使用 `and`，避免不必要的嵌套。",
        "sort_order": 2,
    },
    {
        "level_id": 10,
        "type": "填空题",
        "content": "执行代码：<br><code>a = 0<br>if a == 0:<br>&nbsp;&nbsp;&nbsp;&nbsp;a += 1<br>&nbsp;&nbsp;&nbsp;&nbsp;if a == 1:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;a += 2<br>print(a)</code><br>输出结果是 ",
        "options": None,
        "answer": "3",
        "knowledge_meaning": "外层 a==0 成立，a变成1；继续往下走遇到内层 if a==1，条件成立，a变成1+2=3。",
        "knowledge_rule": "代码是自上而下执行的，外层修改了变量的值，内层使用的就是修改后的新值。",
        "knowledge_error": "不要拿初始值 a=0 去判断内层的 if！变量的值是在动态变化的。",
        "knowledge_example": "程序执行过程：0 -> 1 -> 3",
        "sort_order": 3,
    },
    {
        "level_id": 10,
        "type": "选择题",
        "content": "关于嵌套条件，在排版时最容易出现的错误是什么？",
        "options": [{"letter": "A", "text": "变量名写错"}, {"letter": "B", "text": "忘记导入模块"}, {"letter": "C", "text": "条件全部为真"}, {"letter": "D", "text": "缩进混乱导致逻辑错乱"}],
        "answer": "D",
        "knowledge_meaning": "嵌套越深，对缩进的要求就越严格。少缩进或多缩进，会完全改变代码的执行流。",
        "knowledge_rule": "Python强制使用缩进来划分代码块，因此缩进就是逻辑本身。",
        "knowledge_error": "一旦缩进对齐错误，原本属于内层的代码可能会被解析到外层，导致难以排查的Bug。",
        "knowledge_example": "多使用IDE的自动缩进和格式化工具(如Shift+Tab回退缩进)。",
        "sort_order": 4,
    },
    {
        "level_id": 11,
        "type": "选择题",
        "content": "在Python中，如果直接将变量作为条件（如 <code>if x:</code>），下列哪个值会被判定为 <code>False</code>？",
        "options": [{"letter": "A", "text": "<code>\"0\"</code> (字符串)"}, {"letter": "B", "text": "<code>[1]</code> (列表)"}, {"letter": "C", "text": "<code>0</code> (整数)"}, {"letter": "D", "text": "<code>-1</code> (整数)"}],
        "answer": "C",
        "knowledge_meaning": "Python中，数字 0 被视为 False。非零数字（包括-1）都是 True。",
        "knowledge_rule": "常用的 False 隐式值：0, 0.0, \"\"(空字符串), [](空列表), {}(空字典), None。",
        "knowledge_error": "初学者常以为字符串 `\"0\"` 是 False。只要字符串不为空（里面有字符），哪怕是\"0\"或\"False\"，它就是True！",
        "knowledge_example": "<code>if 0:</code> 不会执行，<code>if \"0\":</code> 会执行。",
        "sort_order": 0,
    },
    {
        "level_id": 11,
        "type": "判断题",
        "content": "代码 <code>if \"\":</code> 中的条件被认为是 <code>True</code>。",
        "options": None,
        "answer": "false",
        "knowledge_meaning": "空字符串 `\"\"` 在布尔语境下会被转换为 False。",
        "knowledge_rule": "所有为空的数据结构（空列表、空元组、空字符串、空字典、空集合）都是 False。",
        "knowledge_error": "非空为真，空为假。非常适合用来检查用户是否输入了内容。",
        "knowledge_example": "<code>name = \"\"<br>if not name: print(\"名字不能为空\")</code>",
        "sort_order": 1,
    },
    {
        "level_id": 11,
        "type": "填空题",
        "content": "执行代码：<br><code>a = []<br>if a:<br>&nbsp;&nbsp;&nbsp;&nbsp;res = \"满\"<br>else:<br>&nbsp;&nbsp;&nbsp;&nbsp;res = \"空\"</code><br>res 的值是 ",
        "options": None,
        "answer": "空",
        "knowledge_meaning": "`a` 是一个空列表 `[]`，被视为 False，因此走 else 分支。",
        "knowledge_rule": "利用 `if 列表:` 可以非常优雅地判断列表是否为空，无需使用 `len(a) > 0`。",
        "knowledge_error": "写成 `if len(a) > 0:` 虽然对，但不符合Pythonic（优雅的Python代码）风格。",
        "knowledge_example": "推荐写法：<code>if a:</code> 而不是 <code>if len(a) != 0:</code>",
        "sort_order": 2,
    },
    {
        "level_id": 11,
        "type": "填空题",
        "content": "执行代码：<br><code>if \"False\":<br>&nbsp;&nbsp;&nbsp;&nbsp;ans = \"T\"<br>else:<br>&nbsp;&nbsp;&nbsp;&nbsp;ans = \"F\"</code><br>ans 的值是 ",
        "options": None,
        "answer": "T",
        "knowledge_meaning": "\"False\" 是一个包含5个字母的字符串，不是空的！非空字符串即为 True。",
        "knowledge_rule": "带引号的布尔词只是普通字符串，不要被文字含义迷惑。",
        "knowledge_error": "很多人会条件反射地认为它代表假，这是极易踩坑的地方。",
        "knowledge_example": "只有不带引号的 <code>False</code> 才是真正的假。",
        "sort_order": 3,
    },
    {
        "level_id": 11,
        "type": "选择题",
        "content": "关于 <code>None</code>，以下哪个表达式等价于检查变量 <code>x</code> 是不是 <code>None</code>？",
        "options": [{"letter": "A", "text": "<code>if x == False:</code>"}, {"letter": "B", "text": "<code>if x == 0:</code>"}, {"letter": "C", "text": "<code>if x == \"\":</code>"}, {"letter": "D", "text": "<code>if x is None:</code>"}],
        "answer": "D",
        "knowledge_meaning": "None 是Python中一个特殊类型（NoneType），代表\"什么都没有\"。",
        "knowledge_rule": "判断是否为None，官方推荐使用身份运算符 `is`，即 `if x is None:`。",
        "knowledge_error": "None不是0，不是False，更不是空字符串，它就是单独存在的None。",
        "knowledge_example": "<code>if x is not None:</code> （判断x有实际值）",
        "sort_order": 4,
    },
    {
        "level_id": 12,
        "type": "选择题",
        "content": "执行代码：<code>res = 10 if 5 > 3 else 20</code>，res 的值是多少？",
        "options": [{"letter": "A", "text": "10"}, {"letter": "B", "text": "20"}, {"letter": "C", "text": "5"}, {"letter": "D", "text": "3"}],
        "answer": "A",
        "knowledge_meaning": "这是Python的三元条件表达式。因为 5>3 为True，所以返回 if 前面的值 10。",
        "knowledge_rule": "语法格式：`为真时的值 if 条件 else 为假时的值`。",
        "knowledge_error": "不要和C/Java里的 `条件 ? 真值 : 假值` 搞混，Python把条件写在中间。",
        "knowledge_example": "<code>status = \"成年\" if age >= 18 else \"未成年\"</code>",
        "sort_order": 0,
    },
    {
        "level_id": 12,
        "type": "判断题",
        "content": "三元条件表达式 (<code>A if cond else B</code>) 中，可以嵌入 <code>elif</code> 逻辑。",
        "options": None,
        "answer": "false",
        "knowledge_meaning": "三元表达式只支持简单的 if-else 双向分支，不支持 elif。",
        "knowledge_rule": "如果需要多分支，必须使用标准的多行 if-elif-else 语句，或者嵌套三元表达式（极度不推荐）。",
        "knowledge_error": "尝试在单行表达式里写 elif 会导致 SyntaxError。",
        "knowledge_example": "不推荐的嵌套写法：<code>A if c1 else (B if c2 else C)</code>，可读性很差。",
        "sort_order": 1,
    },
    {
        "level_id": 12,
        "type": "填空题",
        "content": "执行代码：<br><code>a = 5<br>b = 3<br>if a > 2 and b < 5:<br>&nbsp;&nbsp;&nbsp;&nbsp;c = a + b<br>else:<br>&nbsp;&nbsp;&nbsp;&nbsp;c = a - b</code><br>c 的值是 ",
        "options": None,
        "answer": "8",
        "knowledge_meaning": "a>2(True) 且 b<5(True)，两边都成立，and结果为True。执行 c = 5 + 3 = 8。",
        "knowledge_rule": "条件分支经常结合逻辑运算符 `and`, `or`, `not` 一起使用。",
        "knowledge_error": "and 需要左右两边都是 True 整体才算 True。",
        "knowledge_example": "如果改为 <code>a > 2 or b > 5</code>，结果依然为True。",
        "sort_order": 2,
    },
    {
        "level_id": 12,
        "type": "选择题",
        "content": "有如下代码：<br><code>if not (x > 10): print(\"A\")</code><br>如果想让它输出 \"A\"，x 的值可以是？",
        "options": [{"letter": "A", "text": "15"}, {"letter": "B", "text": "5"}, {"letter": "C", "text": "11"}, {"letter": "D", "text": "100"}],
        "answer": "B",
        "knowledge_meaning": "`not (x > 10)` 要为 True，说明 `x > 10` 必须为 False。所以 x 不能大于 10。",
        "knowledge_rule": "`not` 会将条件的布尔值取反。`not (x > 10)` 在数学上等价于 `x <= 10`。",
        "knowledge_error": "遇到 not 时，先算括号里面的结果，然后再翻转真假。",
        "knowledge_example": "当 x=5 时，5>10为False，not False即为True。",
        "sort_order": 3,
    },
    {
        "level_id": 12,
        "type": "填空题",
        "content": "执行下面这行紧凑的代码：<br><code>x = \"偶\" if 8 % 2 == 0 else \"奇\"</code><br>x 的值是 ",
        "options": None,
        "answer": "偶",
        "knowledge_meaning": "8 % 2 的余数是 0，0 == 0 为 True，所以取 if 前面的值 \"偶\"。",
        "knowledge_rule": "三元表达式非常适合给变量做快速赋值。",
        "knowledge_error": "先计算条件 `8 % 2 == 0`，再决定选用前面还是后面的值。",
        "knowledge_example": "这是代替简单 `if-else` 给单个变量赋值的最佳实践方案。",
        "sort_order": 4,
    },
    {
        "level_id": 13,
        "type": "选择题",
        "content": "执行代码：<br><code>for item in [1, 2, 3]:<br>&nbsp;&nbsp;&nbsp;&nbsp;print(item)</code><br>循环体会执行几次？",
        "options": [{"letter": "A", "text": "1 次"}, {"letter": "B", "text": "2 次"}, {"letter": "C", "text": "3 次"}, {"letter": "D", "text": "4 次"}],
        "answer": "C",
        "knowledge_meaning": "列表里有 3 个元素，for 会依次取出每个元素，所以循环体执行 3 次。",
        "knowledge_rule": "for ... in ... 的本质是“从可迭代对象里一个一个取值”。对象里有几个元素，就会跑几轮。",
        "knowledge_error": "很多人会把“元素值 1、2、3”误看成“执行到 3 就停”，其实这里看的是元素个数。",
        "knowledge_example": "<code>for x in [10, 20]:</code><br><code>&nbsp;&nbsp;&nbsp;&nbsp;print(x)</code><br>会执行 2 次。",
        "sort_order": 0,
    },
    {
        "level_id": 13,
        "type": "判断题",
        "content": "在代码 <code>for letter in \"hi\":</code> 中，变量 <code>letter</code> 会先后取到 <code>h</code> 和 <code>i</code>。",
        "options": None,
        "answer": "true",
        "knowledge_meaning": "字符串也能被 for 逐个字符遍历，所以会先拿到 h，再拿到 i。",
        "knowledge_rule": "列表、字符串、元组等都可以被 for 遍历。字符串遍历时，一次拿到一个字符。",
        "knowledge_error": "不要以为 for 只能遍历数字列表，字符串同样可以一位一位地取。",
        "knowledge_example": "<code>for ch in \"cat\":</code><br><code>&nbsp;&nbsp;&nbsp;&nbsp;print(ch)</code><br>依次输出 c、a、t。",
        "sort_order": 1,
    },
    {
        "level_id": 13,
        "type": "填空题",
        "content": "执行代码：<br><code>total = 0<br>for n in [1, 2, 3]:<br>&nbsp;&nbsp;&nbsp;&nbsp;total += n<br>print(total)</code><br>输出结果是 ",
        "options": None,
        "answer": "6",
        "knowledge_meaning": "total 从 0 开始，三轮分别加上 1、2、3，最后得到 6。",
        "knowledge_rule": "循环里改变量时，要记住每一轮都基于“上一轮后的新值”继续算。",
        "knowledge_error": "不要把每次都当成从 0 重新开始，这种题最容易漏掉“累计”的过程。",
        "knowledge_example": "变化过程：<code>0 → 1 → 3 → 6</code>。",
        "sort_order": 2,
    },
    {
        "level_id": 13,
        "type": "选择题",
        "content": "下面哪段代码是正确的 for 循环写法？",
        "options": [{"letter": "A", "text": "<code>for x in [1, 2, 3]</code>"}, {"letter": "B", "text": "<code>for x in [1, 2, 3]:</code>"}, {"letter": "C", "text": "<code>for (x in [1, 2, 3]):</code>"}, {"letter": "D", "text": "<code>for x = [1, 2, 3]:</code>"}],
        "answer": "B",
        "knowledge_meaning": "正确写法必须包含关键字 for、in、可迭代对象和结尾的冒号。",
        "knowledge_rule": "Python 的 for 语句格式是 <code>for 变量 in 对象:</code>。",
        "knowledge_error": "最常见错误是漏掉冒号，或者把 in 错写成 =。",
        "knowledge_example": "<code>for name in names:</code>",
        "sort_order": 3,
    },
    {
        "level_id": 13,
        "type": "填空题",
        "content": "执行代码：<br><code>count = 0<br>for _ in [\"a\", \"b\", \"c\", \"d\"]:<br>&nbsp;&nbsp;&nbsp;&nbsp;count += 1<br>print(count)</code><br>输出结果是 ",
        "options": None,
        "answer": "4",
        "knowledge_meaning": "列表里有 4 个元素，所以 count 会累加 4 次。",
        "knowledge_rule": "变量名写成 <code>_</code> 时，通常表示“这个值我不关心，只关心循环会跑几次”。",
        "knowledge_error": "不要被 a、b、c、d 的内容干扰，这题重点是轮数，不是元素本身。",
        "knowledge_example": "<code>for _ in [10, 20]:</code><br><code>&nbsp;&nbsp;&nbsp;&nbsp;count += 1</code><br>最终会加 2 次。",
        "sort_order": 4,
    },
    {
        "level_id": 14,
        "type": "选择题",
        "content": "<code>range(4)</code> 生成的数字序列是？",
        "options": [{"letter": "A", "text": "0, 1, 2, 3"}, {"letter": "B", "text": "1, 2, 3, 4"}, {"letter": "C", "text": "0, 1, 2, 3, 4"}, {"letter": "D", "text": "4"}],
        "answer": "A",
        "knowledge_meaning": "range(4) 从 0 开始，到 4 之前结束，所以是 0、1、2、3。",
        "knowledge_rule": "<code>range(stop)</code> 会生成从 0 到 <code>stop - 1</code> 的整数。",
        "knowledge_error": "新手最容易把 4 也算进去，但 range 的右边界是“取不到”的。",
        "knowledge_example": "<code>range(3)</code> 是 0、1、2，不包含 3。",
        "sort_order": 0,
    },
    {
        "level_id": 14,
        "type": "填空题",
        "content": "执行代码：<br><code>total = 0<br>for i in range(1, 5):<br>&nbsp;&nbsp;&nbsp;&nbsp;total += i<br>print(total)</code><br>输出结果是 ",
        "options": None,
        "answer": "10",
        "knowledge_meaning": "range(1, 5) 会得到 1、2、3、4，把它们加起来就是 10。",
        "knowledge_rule": "<code>range(start, stop)</code> 包含 start，不包含 stop。",
        "knowledge_error": "不要把 5 也加进去，停在 5 之前是这类题最关键的点。",
        "knowledge_example": "<code>range(2, 5)</code> 是 2、3、4。",
        "sort_order": 1,
    },
    {
        "level_id": 14,
        "type": "判断题",
        "content": "<code>range(2, 6)</code> 生成的序列中包含数字 <code>6</code>。",
        "options": None,
        "answer": "false",
        "knowledge_meaning": "range(2, 6) 的最后一个数是 5，不会包含 6。",
        "knowledge_rule": "range 总是“左边取到，右边取不到”。",
        "knowledge_error": "这和数学里的区间概念不同，写代码时要强迫自己记住 stop 只是终点，不是成员。",
        "knowledge_example": "<code>range(0, 2)</code> 只有 0 和 1。",
        "sort_order": 2,
    },
    {
        "level_id": 14,
        "type": "选择题",
        "content": "<code>range(0, 10, 2)</code> 生成的数字序列是？",
        "options": [{"letter": "A", "text": "1, 3, 5, 7, 9"}, {"letter": "B", "text": "0, 2, 4, 6, 8, 10"}, {"letter": "C", "text": "0, 2, 4, 6, 8"}, {"letter": "D", "text": "2, 4, 6, 8, 10"}],
        "answer": "C",
        "knowledge_meaning": "从 0 开始，每次加 2，到 10 之前停止，所以得到 0、2、4、6、8。",
        "knowledge_rule": "<code>range(start, stop, step)</code> 中第三个参数表示“每次跳多少”。",
        "knowledge_error": "不要把终点 10 算进去，也不要忘了它是从 0 起步。",
        "knowledge_example": "<code>range(1, 6, 2)</code> 会得到 1、3、5。",
        "sort_order": 3,
    },
    {
        "level_id": 14,
        "type": "填空题",
        "content": "执行代码：<br><code>count = 0<br>for _ in range(3):<br>&nbsp;&nbsp;&nbsp;&nbsp;count += 1<br>print(count)</code><br>输出结果是 ",
        "options": None,
        "answer": "3",
        "knowledge_meaning": "range(3) 会让循环跑 3 轮，所以 count 最后变成 3。",
        "knowledge_rule": "想让一段代码固定执行 N 次，用 <code>for _ in range(N):</code> 最直接。",
        "knowledge_error": "很多人会误以为 range(3) 代表“从 1 到 3”，其实它只是让循环跑 3 次。",
        "knowledge_example": "<code>for _ in range(5):</code> 表示执行 5 次。",
        "sort_order": 4,
    },
    {
        "level_id": 15,
        "type": "判断题",
        "content": "<code>while</code> 循环会在条件为 <code>True</code> 时重复执行代码块。",
        "options": None,
        "answer": "true",
        "knowledge_meaning": "while 的核心就是“条件还成立，就继续做”。",
        "knowledge_rule": "while 每轮开始前都会重新判断一次条件。条件为真才进循环体。",
        "knowledge_error": "不要把 while 想成“只判断一次”，它是每轮都重新判断。",
        "knowledge_example": "<code>while x < 3:</code> 只要 x 还小于 3，就继续执行。",
        "sort_order": 0,
    },
    {
        "level_id": 15,
        "type": "填空题",
        "content": "执行代码：<br><code>x = 1<br>count = 0<br>while x < 4:<br>&nbsp;&nbsp;&nbsp;&nbsp;count += 1<br>&nbsp;&nbsp;&nbsp;&nbsp;x += 1<br>print(count)</code><br>输出结果是 ",
        "options": None,
        "answer": "3",
        "knowledge_meaning": "x 会经历 1、2、3 三次满足条件，因此 count 累加 3 次。",
        "knowledge_rule": "做 while 题时，最稳的方法是把“条件”和“变量变化”一起盯住。",
        "knowledge_error": "容易只看 x 最后变成 4，就误判成执行 4 次。实际上 x=4 时已经不进循环了。",
        "knowledge_example": "轮次是：x=1、2、3 进循环；x=4 停止。",
        "sort_order": 1,
    },
    {
        "level_id": 15,
        "type": "选择题",
        "content": "下面哪种做法最能避免 <code>while</code> 循环一直停不下来？",
        "options": [{"letter": "A", "text": "把冒号删掉"}, {"letter": "B", "text": "在循环里更新参与判断的变量"}, {"letter": "C", "text": "把 while 改成 if"}, {"letter": "D", "text": "让条件永远为 True"}],
        "answer": "B",
        "knowledge_meaning": "如果循环里的变量一直不变，条件可能永远成立，程序就会一直重复。",
        "knowledge_rule": "while 常常需要在循环体里修改条件相关的变量，让程序有机会停下来。",
        "knowledge_error": "新手最常见的 bug 就是忘了写 <code>x += 1</code> 这类更新语句。",
        "knowledge_example": "<code>while x < 5:</code><br><code>&nbsp;&nbsp;&nbsp;&nbsp;x += 1</code>",
        "sort_order": 2,
    },
    {
        "level_id": 15,
        "type": "填空题",
        "content": "执行代码：<br><code>count = 0<br>while False:<br>&nbsp;&nbsp;&nbsp;&nbsp;count += 1<br>print(count)</code><br>输出结果是 ",
        "options": None,
        "answer": "0",
        "knowledge_meaning": "条件一开始就是 False，所以循环体一次也不会执行。",
        "knowledge_rule": "while 会先判断条件，再决定要不要执行代码块。",
        "knowledge_error": "不要想当然地进入循环。看到 while 先问自己：第一轮条件成立吗？",
        "knowledge_example": "<code>while 3 &lt; 2:</code> 也是 0 次都不执行。",
        "sort_order": 3,
    },
    {
        "level_id": 15,
        "type": "选择题",
        "content": "下面哪段代码是正确的 while 语句写法？",
        "options": [{"letter": "A", "text": "<code>while x &lt; 5</code>"}, {"letter": "B", "text": "<code>while (x &lt; 5)</code>"}, {"letter": "C", "text": "<code>while x = 5:</code>"}, {"letter": "D", "text": "<code>while x &lt; 5:</code>"}],
        "answer": "D",
        "knowledge_meaning": "正确写法和 if 一样，条件后要有冒号。",
        "knowledge_rule": "while 语句格式是 <code>while 条件:</code>。",
        "knowledge_error": "A 漏冒号，C 把判断写成赋值，都是初学者常见语法错误。",
        "knowledge_example": "<code>while score &lt; 10:</code>",
        "sort_order": 4,
    },
    {
        "level_id": 16,
        "type": "选择题",
        "content": "<code>break</code> 在循环中的作用是？",
        "options": [{"letter": "A", "text": "立刻结束当前循环"}, {"letter": "B", "text": "跳过本轮，继续下一轮"}, {"letter": "C", "text": "让循环从头开始"}, {"letter": "D", "text": "让条件自动变成 False"}],
        "answer": "A",
        "knowledge_meaning": "break 的意思就是“断开”，一执行就直接跳出当前循环。",
        "knowledge_rule": "break 只负责结束它所在的那一层循环。",
        "knowledge_error": "不要把 break 和 continue 混淆。continue 只是跳过本轮，不是结束整个循环。",
        "knowledge_example": "<code>if x == 3:</code><br><code>&nbsp;&nbsp;&nbsp;&nbsp;break</code>",
        "sort_order": 0,
    },
    {
        "level_id": 16,
        "type": "判断题",
        "content": "<code>continue</code> 会跳过本轮剩余代码，直接进入下一轮循环。",
        "options": None,
        "answer": "true",
        "knowledge_meaning": "continue 的作用是“本轮别往下做了，去下一轮”。",
        "knowledge_rule": "continue 不会结束整个循环，只会结束当前这一轮。",
        "knowledge_error": "有些人看到 continue 就以为循环结束了，其实它只是跳过当前这次。",
        "knowledge_example": "<code>if x == 2:</code><br><code>&nbsp;&nbsp;&nbsp;&nbsp;continue</code>",
        "sort_order": 1,
    },
    {
        "level_id": 16,
        "type": "填空题",
        "content": "执行代码：<br><code>count = 0<br>for i in [1, 2, 3, 4]:<br>&nbsp;&nbsp;&nbsp;&nbsp;if i == 3:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break<br>&nbsp;&nbsp;&nbsp;&nbsp;count += 1<br>print(count)</code><br>输出结果是 ",
        "options": None,
        "answer": "2",
        "knowledge_meaning": "i 为 1、2 时都会让 count 加 1；到 3 时 break，后面不再执行。",
        "knowledge_rule": "break 出现后，当前循环直接结束，连本轮后面的代码也不再执行。",
        "knowledge_error": "不要把 i=3 这一轮也算进去，因为在 count += 1 之前就已经 break 了。",
        "knowledge_example": "执行到 3 时停止，所以只累计了前两轮。",
        "sort_order": 2,
    },
    {
        "level_id": 16,
        "type": "选择题",
        "content": "执行代码：<br><code>for i in [1, 2, 3, 4]:<br>&nbsp;&nbsp;&nbsp;&nbsp;if i == 2:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;continue<br>&nbsp;&nbsp;&nbsp;&nbsp;print(i)</code><br>会打印什么？",
        "options": [{"letter": "A", "text": "1 2 3 4"}, {"letter": "B", "text": "1 3 4"}, {"letter": "C", "text": "2 3 4"}, {"letter": "D", "text": "只有 2"}],
        "answer": "B",
        "knowledge_meaning": "i=2 时被 continue 跳过，所以只会打印 1、3、4。",
        "knowledge_rule": "continue 会跳过当前轮剩余代码，所以这一轮里的 print 不会执行。",
        "knowledge_error": "别把 continue 当成 break，它不会阻止后面的 3 和 4 继续执行。",
        "knowledge_example": "跳过哪一轮，就少打印哪一个值。",
        "sort_order": 3,
    },
    {
        "level_id": 16,
        "type": "判断题",
        "content": "在嵌套循环里，<code>break</code> 默认只会跳出它所在的那一层循环。",
        "options": None,
        "answer": "true",
        "knowledge_meaning": "break 只认识自己当前所在的循环，不会自动把外层也一起结束。",
        "knowledge_rule": "嵌套循环里，break 只结束最近的一层循环。",
        "knowledge_error": "这类题很容易把“跳出当前层”误看成“整个程序都停了”。",
        "knowledge_example": "内层 break 结束内层，外层还会继续下一轮。",
        "sort_order": 4,
    },
    {
        "level_id": 17,
        "type": "选择题",
        "content": "什么叫“循环嵌套”？",
        "options": [{"letter": "A", "text": "一个循环写两次"}, {"letter": "B", "text": "把 while 改成 for"}, {"letter": "C", "text": "循环里写 if"}, {"letter": "D", "text": "在一个循环里面再放一个循环"}],
        "answer": "D",
        "knowledge_meaning": "循环嵌套就是“外层每跑一轮，内层完整跑一遍”。",
        "knowledge_rule": "嵌套结构中，内层循环属于外层循环体的一部分。",
        "knowledge_error": "不要把“循环里有判断”误认为循环嵌套，嵌套要求里面还是循环。",
        "knowledge_example": "<code>for row in rows:</code><br><code>&nbsp;&nbsp;&nbsp;&nbsp;for col in cols:</code>",
        "sort_order": 0,
    },
    {
        "level_id": 17,
        "type": "填空题",
        "content": "执行代码：<br><code>count = 0<br>for a in [1, 2]:<br>&nbsp;&nbsp;&nbsp;&nbsp;for b in [\"x\", \"y\", \"z\"]:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;count += 1<br>print(count)</code><br>输出结果是 ",
        "options": None,
        "answer": "6",
        "knowledge_meaning": "外层有 2 轮，每一轮内层都跑 3 次，所以总共是 2 × 3 = 6。",
        "knowledge_rule": "嵌套循环的总次数，常常可以理解成“外层轮数 × 内层轮数”。",
        "knowledge_error": "不要只看到内层 3 次，也不要只看到外层 2 次，两层要一起算。",
        "knowledge_example": "如果外层 4 次、内层 5 次，总共就是 20 次。",
        "sort_order": 1,
    },
    {
        "level_id": 17,
        "type": "判断题",
        "content": "在嵌套循环中，外层循环每执行一轮，内层循环都会从头完整执行一遍。",
        "options": None,
        "answer": "true",
        "knowledge_meaning": "这正是嵌套循环最核心的运行方式。",
        "knowledge_rule": "内层循环不是“接着上次继续”，而是外层每一轮都会重新从第一步开始。",
        "knowledge_error": "新手常误以为内层跑完一次就结束了，其实它会随着外层重复多次。",
        "knowledge_example": "外层 2 轮时，内层会“完整跑一遍”发生 2 次。",
        "sort_order": 2,
    },
    {
        "level_id": 17,
        "type": "选择题",
        "content": "执行代码：<br><code>for x in [1, 2]:<br>&nbsp;&nbsp;&nbsp;&nbsp;for y in [\"A\", \"B\"]:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(x, y)</code><br>最先打印的两组内容是？",
        "options": [{"letter": "A", "text": "1 A，然后 1 B"}, {"letter": "B", "text": "1 A，然后 2 A"}, {"letter": "C", "text": "2 A，然后 2 B"}, {"letter": "D", "text": "1 B，然后 2 B"}],
        "answer": "A",
        "knowledge_meaning": "x=1 时，内层 y 会完整跑 A、B，所以最先是 1 A、1 B。",
        "knowledge_rule": "做嵌套题要固定住外层当前值，再把内层完整跑一遍。",
        "knowledge_error": "很多人会太快切到 x=2，漏掉了 x=1 这一轮里还没跑完的内层。",
        "knowledge_example": "顺序一般是：固定外层，扫完内层；再换下一个外层。",
        "sort_order": 3,
    },
    {
        "level_id": 17,
        "type": "填空题",
        "content": "执行代码：<br><code>total = 0<br>for row in range(2):<br>&nbsp;&nbsp;&nbsp;&nbsp;for col in range(2):<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;total += 1<br>print(total)</code><br>输出结果是 ",
        "options": None,
        "answer": "4",
        "knowledge_meaning": "外层 2 轮，内层每轮 2 次，所以 total 一共加了 4 次。",
        "knowledge_rule": "看到两层都用 range(2)，就可以快速想到是 2 × 2。",
        "knowledge_error": "不要把 range(2) 看成 2 和 2 两个值本身，重点是它代表“执行两轮”。",
        "knowledge_example": "<code>range(3)</code> 搭配 <code>range(4)</code> 时，总次数是 12。",
        "sort_order": 4,
    },
    {
        "level_id": 18,
        "type": "填空题",
        "content": "执行代码：<br><code>total = 0<br>for n in range(1, 6):<br>&nbsp;&nbsp;&nbsp;&nbsp;total += n<br>print(total)</code><br>输出结果是 ",
        "options": None,
        "answer": "15",
        "knowledge_meaning": "range(1, 6) 是 1、2、3、4、5，加起来等于 15。",
        "knowledge_rule": "综合题依然要拆开做：先看序列，再看循环次数，最后看变量怎么累加。",
        "knowledge_error": "不要被“综合挑战”吓住，本质仍然是前面学过的 range 和累加。",
        "knowledge_example": "1+2+3+4+5 = 15。",
        "sort_order": 0,
    },
    {
        "level_id": 18,
        "type": "选择题",
        "content": "下面哪段代码会输出 0、1、2 这三个数字？",
        "options": [{"letter": "A", "text": "<code>for i in range(1, 3):<br>&nbsp;&nbsp;&nbsp;&nbsp;print(i)</code>"}, {"letter": "B", "text": "<code>for i in range(3):<br>&nbsp;&nbsp;&nbsp;&nbsp;print(i)</code>"}, {"letter": "C", "text": "<code>for i in range(1, 4):<br>&nbsp;&nbsp;&nbsp;&nbsp;print(i)</code>"}, {"letter": "D", "text": "<code>for i in range(0, 2):<br>&nbsp;&nbsp;&nbsp;&nbsp;print(i)</code>"}],
        "answer": "B",
        "knowledge_meaning": "range(3) 刚好会从 0 打到 2。",
        "knowledge_rule": "想打印 0 到 n-1，用 <code>range(n)</code> 最直接。",
        "knowledge_error": "A 和 D 都少一个数，C 则从 1 开始，不符合要求。",
        "knowledge_example": "<code>range(5)</code> 对应 0、1、2、3、4。",
        "sort_order": 1,
    },
    {
        "level_id": 18,
        "type": "判断题",
        "content": "执行代码 <code>n = 3<br>while n &gt; 0:<br>&nbsp;&nbsp;&nbsp;&nbsp;n -= 1</code> 后，循环最终会停下来。",
        "options": None,
        "answer": "true",
        "knowledge_meaning": "n 每轮都会减 1，所以会经历 3、2、1，最后变成 0，条件不再成立。",
        "knowledge_rule": "只要循环里的更新让条件朝“终止方向”前进，while 就能正常结束。",
        "knowledge_error": "很多人只盯着 while，不看里面的变化语句，结果判断不出会不会停。",
        "knowledge_example": "当 n 变成 0 时，<code>n &gt; 0</code> 为假，循环结束。",
        "sort_order": 2,
    },
    {
        "level_id": 18,
        "type": "填空题",
        "content": "执行代码：<br><code>total = 0<br>for i in range(1, 6):<br>&nbsp;&nbsp;&nbsp;&nbsp;if i % 2 == 0:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;continue<br>&nbsp;&nbsp;&nbsp;&nbsp;total += i<br>print(total)</code><br>输出结果是 ",
        "options": None,
        "answer": "9",
        "knowledge_meaning": "偶数 2 和 4 被 continue 跳过，只加上 1、3、5，所以得到 9。",
        "knowledge_rule": "continue 常用于“跳过不想处理的情况，只保留满足条件的值”。",
        "knowledge_error": "如果没看出 continue 会跳过偶数，就容易把 1 到 5 全部加进去。",
        "knowledge_example": "保留下来的数是 1、3、5，因此 1+3+5=9。",
        "sort_order": 3,
    },
    {
        "level_id": 18,
        "type": "选择题",
        "content": "如果你想让程序把“你好”打印 3 次，下面哪段代码最合适？",
        "options": [{"letter": "A", "text": "<code>if 3:<br>&nbsp;&nbsp;&nbsp;&nbsp;print(\"你好\")</code>"}, {"letter": "B", "text": "<code>while 3:<br>&nbsp;&nbsp;&nbsp;&nbsp;print(\"你好\")</code>"}, {"letter": "C", "text": "<code>for i in range(4):<br>&nbsp;&nbsp;&nbsp;&nbsp;print(\"你好\")</code>"}, {"letter": "D", "text": "<code>for i in range(3):<br>&nbsp;&nbsp;&nbsp;&nbsp;print(\"你好\")</code>"}],
        "answer": "D",
        "knowledge_meaning": "range(3) 正好控制循环执行 3 次，是最标准的做法。",
        "knowledge_rule": "固定次数重复任务，优先想到 <code>for ... in range(...)</code>。",
        "knowledge_error": "B 中 <code>while 3</code> 会一直为真，容易造成死循环；C 会打印 4 次。",
        "knowledge_example": "<code>for _ in range(3):</code><br><code>&nbsp;&nbsp;&nbsp;&nbsp;print(\"你好\")</code>",
        "sort_order": 4,
    },
]
